version: "3"

networks:
  tt_net:
    driver: bridge

services:
  grafana:
    image: grafana/grafana
    # first install kairosdb datasource plugin, then run grafana
    entrypoint: /bin/sh
    command: ["-c", "grafana-cli plugins install grafana-kairosdb-datasource && /run.sh"]
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"
    restart: always
    ports:
      - "3000:3000"
    networks:
      - tt_net
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret

  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
    networks:
      - tt_net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"

  kairosdb:
    build: .
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"
    restart: always
    ports:
      - "8080:8080"
    networks:
      - tt_net
    environment:      
      - CASSANDRA_HOSTS=cassandra
      - CASSANDRA_PORT=9042

  cassandra:
    image: cassandra
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"
    restart: always
    ports:
      - "9042:9042"
    volumes:
      - ${PWD}/cassandra-data:/var/lib/cassandra
    networks:
      - tt_net
    environment:
      - CASSANDRA_CLUSTER_NAME=tt-cluster

